config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  
  resources :reservations
  resources :users
  resources :flights
  resources :planes

  
  root to: "flights#index"

  

  get 'flight/:id' => 'flights#show'

end

app/models/plane.rb
class Plane < ActiveRecord::Base
	has_many :flights

	def makeSeats
		seatList = []
		alph = ("A".."Z").to_a
		for i in 0..self.rows - 1
			for k in 0..self.columns - 1
				seatList << (i + 1).to_s + alph[k]
			end
		end
		return seatList
	end
	def numberOfSeats
		makeSeats.length
	end



end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]
  def home
  end
  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:name, :rows, :columns)
    end
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/planes/_form.html.erb
<%= form_for(@plane) do |f| %>
  <% if @plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% @plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rows %><br>
    <%= f.number_field :rows %>
  </div>
  <div class="field">
    <%= f.label :columns %><br>
    <%= f.number_field :columns %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planes/edit.html.erb
<h1>Editing Plane</h1>

<%= render 'form' %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

app/views/planes/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>oatmeal</title>
</head>
<body>
<div id="plane-page">
  <section id="airlineapp">
      <header id="header">
      <table class="table">
        <thead>
          <tr>
          <th><a href="/planes">Planes</a></th>
          <th><a href="/flights">Flights</a></th>
          <th><a href="/admin/sign_in">Admin</a></th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
      </header>

    <section id="main" class="main">
      <table class="table1">
        <thead>
          <tr class="th">
          <th class="title">Oatmeal Airlines</th>
          <th><button class="submit">Create Flight</button></th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
      </section>

      <section id="content">
        <form class="plane-form">
          <div class="box">
            <table class="table2">
              <thead></thead>
              <tbody>
              <tr>
                <td><input id="nameInput" name="name" type="text" placeholder="name" class="text"/></td>
                <td><input id="rows" name="rows" type="text" placeholder="rows" class="text"/></td>
                <td><input id="columns" name="columns" type="text" placeholder="cols" class="text"/></td>
                <td></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td colspan="3"><button class="cancel-button">Cancel</button><span class="space"/><button class="submit" type="submit">Save</button></td>

              </tr>       
              </tbody>
            </table>
          </div>
        </form>
      </section>



      <div id="planeName" class="page">
        <h1>plane name</h1>
      </div>  



    <div id="table" class="flight-seat"></div>
    
    <script>

    $("#table").hide();

    $(".submit").click( function()
      {

         // choice = this.id; 
         //  $(".selection").html("Your choice: <h1>" + choice + "</h1>");
         //  $("#reservation-form").show();
         //  $("#seatInput").val(choice);
         makeTable();
         $("#planeName").html("<h1>" + $("#nameInput").val() + "</h1>");
         $("#table").show();
      });
      var makeTable = function(){
          var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
          var rows = $("#rows").val()  || 1;      //1-30
          var columns = $("#columns").val()  || 1;   //A-H
          var result = "";
          result += "<table class='table4'>";

          result += "<thead>";
          result += "<tr>";
          result +="<td></td>";
          for (var x = 0; x < columns; x++) {
            result += "<td>";
            result += alphabet[x];
            result += "</td>";  
          }    
          result += "</tr>";
          result += "</thead>"

          result += "<tbody>";
          for (var y = 0; y < rows; y++) {
            result += "<tr>"; 
            result += "<td>";
            result += y+1;
            result += "</td>"; 
          for (var x = 0; x < columns; x++) {
              result += "<td>";
              result += "<button class='reserved'><span>"
              result += "avail";
              result += "</span></button>"
              result += "</td>";
            }
            result += "</tr>";
          }
          result += "</tbody>";
          result += "</table>";
          $('#table').html(result);
          console.log(result);
      } 

  </script>
 </section>

</div>
</body>
</html>


<!-- <p id="notice"><%= notice %></p>

<h1>Listing Planes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rows</th>
      <th>Columns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planes.each do |plane| %>
      <tr>
        <td><%= plane.name %></td>
        <td><%= plane.rows %></td>
        <td><%= plane.columns %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plane', new_plane_path %> -->

app/views/planes/new.html.erb
<h1>New Plane</h1>

<%= render 'form' %>

<%= link_to 'Back', planes_path %>

app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plane.name %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @plane.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @plane.columns %>
</p>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>