config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  
  resources :reservations
  resources :users
  resources :flights
  resources :planes

  
  root to: "flights#index"

  

  get 'flight/:id' => 'flights#show'

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :plane
  has_many :reservations


	def listSeats
		return self.plane.makeSeats
	end
	def listAvailableSeats
		list = listSeats
		self.reservations.each do |k|
   			list.delete(k.seat)
		end
		return list
	end
	def listReservedSeats
		list = []
		self.reservations.each do |k|
   			list.push(k.seat)
		end
		return list
	end
	def availableSeatsNumber
		listAvailableSeats.length
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @user = User.new #_______________________________
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:origin, :destination, :date, :plane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :plane_id %><br>
    <%= f.text_field :plane_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>oatmeal</title>

</head>
<body>
  <div id="search-page">
    <div id="flight-page">
      <section id="airlineapp">
          <header id="header">
          <table class="table">
            <thead>
              <tr>
              <th><a href="">Planes</a></th>
              <th><a href="">Flights</a></th>
              <th><a href="">Admin</a></th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
          </header>


      <section id="main" class="main">
        <table class="table1">
          <thead>
            <tr class="th">
            <th class="title">Oatmeal Airlines</th>
            <th><button id="searchButton" class="submit">Search Flights</button></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
        </section>

        <section id="content">
          <div class="box">
        <table class="table2">
          <thead></thead>
          <tbody>
          <tr>      
            <td><input type="text" placeholder="from" class="text"/></td>
            <td><input type="text" placeholder="to" class="text"/></td>
          </tr>
          <tr>
            <td></td>
            <td><button class="submit1">Cancel</button><span class="space"/><button class="submit1">Save</button></td>
          </tr>       
          </tbody>
        </table>
          </div>
        </section>

         

        
          <div class="page">
            <h1>Flights</h1>
         
              <table class="flight-list">
                <tr>
                  <th>
                    Date
                  </th>
                  <th>
                    Flight
                  </th>
                  <th>
                    From>To
                  </th>
                  <th>
                    Plane
                  </th>
                  <th>
                    Seats
                  </th>
              </tr>
              

              </table>
          </div>  
       

          <footer id="footer"></footer>
      </section>

    </div>
</div>

<script>
$("#searchButton").click( function()
{
  l = searchFlights();
  oatmeal.flightsearchview.render();
});
         

 
</script>
</body>
</html>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/search.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>oatmeal</title>

</head>
<body>
  
    
      <section id="airlineapp">
          <header id="header">
          <table class="table">
            <thead>
              <tr>
              <th><a href="">Planes</a></th>
              <th><a href="">Flights</a></th>
              <th><a href="">Admin</a></th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
          </header>


      <section id="main" class="main">
        <table class="table1">
          <thead>
            <tr class="th">
            <th class="title">Virgin Airlines</th>
            <th><button id="searchButton" class="submit">Search Flights</button></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
        </section>

        <section id="content">
          <div class="box">
        <table class="table2">
          <thead></thead>
          <tbody>
          <tr>      
            <td><input type="text" placeholder="from" class="text"/></td>
            <td><input type="text" placeholder="to" class="text"/></td>
          </tr>
          <tr>
            <td></td>
            <td><button class="submit1">Cancel</button><span class="space"/><button class="submit1">Save</button></td>
          </tr>       
          </tbody>
        </table>
          </div>
        </section>

         

        
          <div class="page">
            <h1>Flights</h1>
         <div id="user-search-page">
              <table class="result-list">
                <tr>
                  <th>
                    Date
                  </th>
                  <th>
                    Flight
                  </th>
                  <th>
                    From>To
                  </th>
                  <th>
                    Plane
                  </th>
                  <th>
                    Seats
                  </th>
              </tr>
          </div>

              </table>
          </div>  
       

          <footer id="footer"></footer>
      </section>

    


<script>
$("#searchButton").click( function()
{
  l = searchFlights();
  oatmeal.flightsearchview.render();
});
         

 
</script>
</body>
</html>

app/views/flights/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>oatmeal</title>

</head>
<body>
<div id="reservation-page">
	<section id="airlineapp">
	    <header id="header">
			<table class="table">
				<thead>
					<tr>
					<th style="background-color:white"></th>
					<th><a href="">Search</a></th>
					<th>User name</th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
	    </header>

		<section id="main" class="main">
			<table class="table1">
				<thead>
					<tr class="th">
					<th class="title">Oatmeal Airlines</th>
					<th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
	    </section>

	  <section>
	  	<h2><%= @flight.date %>   Flight <%= @flight.number %>  <%= @flight.origin %>><%= @flight.destination %>  <br>Plane  <%= @flight.plane.name %></h2> 
	  	number of seats on plane:  <%= @flight.plane.numberOfSeats %>
	  	number of seat available:  <%= @flight.availableSeatsNumber %>
	  </section>
	  <div class="selection">
	  </div>
		<form class="reservation-form">
			<input name="usernum" type="text" placeholder="your name" class="text"/>
			<input name="flightnum" type="text" placeholder="flightnum" class="text"/>
			<input id="seatInput" name="seatInput" id="seatInput" type="text" placeholder="seat" class="text"  />


			<button class="submit" type="submit">Book Seat</button>
		</form>
		<section id="seat">
			<div id="seat-table" class="flight-seat">
				<h1>Flights Search Results</h1>
			</div>	
		</section>


	</section>
</div>
  <script>



  	$("#reservation-form").hide();
  	 var flight1 = new oatmeal.Flight({number: "<%= @flight.number %>",
  	 	 numberOfSeats: "<%= @flight.plane.numberOfSeats %>",
  	 	 origin: "<%= @flight.origin %>",
  	 	 destination: "<%= @flight.destination %>",
  	 	 availableSeatsNumber: "<%= @flight.availableSeatsNumber %>",
  	 	 date: "<%= @flight.date %>",
  	 	 listReservedSeats: '<%= @flight.listReservedSeats.to_s %>'
  	 	});
  	// var json = JSON.parse(flight1);
  	// console.log(taken);
  	// flight1.get("obj1").myAttribute1;

  	var s = "";
  	s = "<%= @flight.listReservedSeats.to_s %>";

  	var d = s.replace(/&quot/g, "");
  	var f = d.replace(/;/g, "");
  	var g = f.replace(/[,\[\]]/g, "");
  	var rSeats = g.split(" ");
    var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    var rows = <%= @flight.plane.rows %>;      //1-30
    var columns = <%= @flight.plane.columns %>;   //A-H
    var result = "";
    result += "<table class='table4'>";

    result += "<thead>";
    result += "<tr>";
    result +="<td></td>";
    for (var x = 0; x < columns; x++) {
      result += "<td>";
      result += alphabet[x];
      result += "</td>";  
    }    
    result += "</tr>";
    result += "</thead>"

    result += "<tbody>";
    for (var y = 0; y < rows; y++) {
      result += "<tr>"; 
      result += "<td>";
      result += y+1;
      result += "</td>"; 
    for (var x = 0; x < columns; x++) {
        result += "<td>";
        result += "<button class='try-reserve' id=" + (y + 1) + alphabet[x] + "><span>"
        result += "avail";
        result += "</span></button>"
        result += "</td>";
      }
      result += "</tr>";
    }
    result += "</tbody>";
    result += "</table>";
    $('#seat-table').html(result);
    console.log(result);

    for(var j = 0; j < rSeats.length; j++){
    	// $("#"+rSeats[j]).hide();
      $("#"+rSeats[j]).addClass( "dead" );
    }
var choice;
$(".try-reserve").click( function()
{
   choice = this.id; 
   	$(".selection").html("Your choice: <h1>" + choice + "</h1>");
   	$("#reservation-form").show();
   	$("#seatInput").val(choice);
});
  </script>


</body>
</html>