config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  
  resources :reservations
  resources :users
  resources :flights
  resources :planes

  
  root to: "flights#index"

  

  get 'flight/:id' => 'flights#show'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :flight
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  def home
  end
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:number, :user_id, :flight_id, :seat)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :flight_id %><br>
    <%= f.text_field :flight_id %>
  </div>
  <div class="field">
    <%= f.label :seat %><br>
    <%= f.text_field :seat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>oatmeal</title>
</head>
<body>

<section id="airlineapp">
    <header id="header">
    <table class="table">
      <thead>
        <tr>
        <th style="background-color:white"></th>
        <th><a href="/">Search</a></th>
        <th><a href="/">User name</a></th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
    </header>

  <section id="main" class="main">
    <table class="table1">
      <thead>
        <tr class="th">
        <th class="title">Oatmeal Airlines</th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
    </section>

    <section id="content">
      <div class="box">
    <table class="table2">
      <thead></thead>
      <tbody>
      <tr>      
        <td><input type="text" placeholder="from" class="text"/></td>
        <td><input type="text" placeholder="to" class="text"/></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><button class="cancel-button">Cancel</button><span class="space"/><button class="submit">Save</button></td>
      </tr>       
      </tbody>
    </table>
      </div>
    </section>
</section>
</body>
</html>




<!-- <p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>User</th>
      <th>Flight</th>
      <th>Seat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.number %></td>
        <td><%= reservation.user.name %></td>
        <td><%= reservation.flight.number %></td>
        <td><%= reservation.seat %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>
 -->

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @reservation.number %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user.name %>
</p>

<p>
  <strong>Flight:</strong>
  <%= @reservation.flight.date %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @reservation.seat %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>oatmeal</title>

</head>
<body>

<section id="airlineapp">
    <header id="header">
		<table class="table">
			<thead>
				<tr>
				<th style="background-color:white"></th>
				<th><a href="">Search</a></th>
				<th>User name</th>
				</tr>
			</thead>
			<tbody></tbody>
		</table>
    </header>

	<section id="main" class="main">
		<table class="table1">
			<thead>
				<tr class="th">
				<th class="title">Virgin Airlines</th>
				<th>
				</tr>
			</thead>
			<tbody></tbody>
		</table>
    </section>

  <section>
  	<h2><%= @reservation.flight.date %>   Flight <%= @reservation.flight.number %>  <%= @reservation.flight.origin %>><%= @reservation.flight.destination %></h2>
  </section>

	<section id="seat">
		<div class="seat-table">
			
		</div>	
	</section>

    <footer id="footer"></footer>
</section>

	  <script>
    var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    var rows = 9;      //1-30
    var columns = 10;   //A-H
    var result = "";
    result += "<table class='table4'>";

    result += "<thead>";
    result += "<tr>";
    result +="<td></td>";
    for (var x = 0; x < columns; x++) {
      result += "<td>";
      result += alphabet[x];
      result += "</td>";  
    }    
    result += "</tr>";
    result += "</thead>"

    result += "<tbody>";
    for (var y = 0; y < rows; y++) {
      result += "<tr>"; 
      result += "<td>";
      result += y+1;
      result += "</td>"; 
    for (var x = 0; x < columns; x++) {
        result += "<td>";
        result += "<button class='reserved'><span>"
        result += "avail";
        result += "</span></button>"
        result += "</td>";
      }
      result += "</tr>";
    }
    result += "</tbody>";
    result += "</table>";
    $('#seat-table').html(result);
    console.log(result);
  </script>

</body>
</html>